### ISSUE TITLE
Send, Abort and Save buttons greyed

### ISSUE THREAD

**Issue by MarcusWolschon** [mike-kfed/rcmail-thunderbird-labels#28]
Roundcube 1.2.0
Since rcmail-thunderbird-labels has not a single release yet, I can not name a specific version number for this bug.
git pull says, I'm up to date (2016-07-20)

When composing a message, the "Send", "Abort" and "Save" buttons are greyed and unusable.
There is a Javascript error "TypeError: w is undefined" in tb_labels.
Removing the pluging from config.inc.php makes the user able to SEND MESSAGES AGAIN.
=>Priority: critical (breaks sending any kind of messages in this mail client)
﻿﻿

**Comment by dsoares** [comment]
Hi,
Does it say in which line? I can't find any use of var w in tb_labels.js
I can't reproduce it with the last git version for both Roundcube and rcmail-thunderbird-labels, it works ok.

**Comment by MarcusWolschon** [comment]
Roundcube stable release version 1.2, not git-head and plugin git-head (as there are no releases).
The error message can't be copied as text from Firefox, so I didn't archive any more details.
Currently I'm glad my webmail is usable again for me and my other users even without the labels.

**Comment by mike-kfed** [comment]
First of all stop complaining that there are "no releases", there are 12 right here on github - https://github.com/mike-kfed/rcmail-thunderbird-labels/releases

And master works for all of us von roundcube 1.2.0 without a problem. So please figure out a way to copy the full traceback of the error from your firefox error console, which then might help us find the problem.

The only way to have a problem with a variable called "w" would be using the arbitrary_labels branch and since this is not a release^^ feel free to fix the problem and submit a pull request so that it can become one.

**Comment by MarcusWolschon** [comment]
Sorry, I seem to have completele missed that.
Yes, they are even mentioned on the plugin repository page.
https://plugins.roundcube.net/packages/weird-birds/thunderbird_labels
